# -*- coding: utf-8 -*-
"""Promedio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1StGhiBuu-7r5vy3sK69MozRRKShAQCAf
"""
A= int(input("Ingrese el primer numero: "))
B= int(input("Ingrese el segundo numero: "))
C= int(input("Ingrese el tercer numero: "))
D= int(input("Ingrese el cuarto numero: "))
E= int(input("Ingrese el quinto numero: "))

from statistics import mean
mean([A,B,C,D,E])

#promedio=mean([A,B,C,D,E])
#print(promedio)

'''
A= float(input("Ingrese el primer numero: "))
B= float(input("Ingrese el segundo numero: "))
C= float(input("Ingrese el tercer numero: "))
D= float(input("Ingrese el cuarto numero: "))
E= float(input("Ingrese el quinto numero: "))
'''

